[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
dcarbon_program = "AVABwP8V51iBGJhrJrWLEgUEQhWsQtt8U7yaekBHStQu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = ".wallets/master.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
